module.exports=[
    require("../routers/admin_Router"),
    require("../routers/blood_group_Router"),
    require("../routers/blood_component_Router"),
    require("../routers/user_Router"),
    require("../routers/donor_Router"),
    require("../routers/emp_Router"),
    require("../routers/bbank_Router"),
    require("../routers/stock_Router"),
    require("../routers/request_Router"),
    require("../routers/reqApprv_Router"),
    require("../routers/pagination_Router"),
    require("../routers/camp_Router"),
    require("../routers/appoit_Router")
];